CHANGELOG.md, Dockerfile, netbox_secrets/__init__.py, netbox_secrets/filtersets.py, netbox_secrets/models/secrets.py, netbox_secrets/tests/test_filters.py, setup.py
Fixes #20 
Added contact filterset only when `enable_contacts` is set
=> Added contact filterset

.github/workflows/ci.yml, .github/workflows/python-publish.yml, CHANGELOG.md, README.md, setup.py
=> Prepare for Pypi

netbox_secrets/templates/netbox_secrets/secretrole.html
- Fix secret role secret count 
Close: #24
=> Fixed secret count on secret role object page

netbox_secrets/forms/secrets.py
- Added more fields on secret filter form
Close: #39
=> added more fields in filter forms 

netbox_secrets/views.py
- Do now allow to edit keys when only 1 user key is active
=> Do not edit keys when only 1 user key is active

netbox_secrets/views.py
- The first user cannot create userkey
=> [Fix]: First user cannot create userkey

netbox_secrets/migrations/0004_populate_secrets.py, setup.py
For #44 , I have updated the migration code update the object changes as well.
---
---
---
---
=> Added migrations for object changes from old app

netbox_secrets/api/views.py
Session key view, for retrieving session key, requires urlencoded data to be sent in the request, and this is only parsed properly with the FormParser
#47 
Add FormParser for urlencoded data
---
No form parser, so no urlencoded data is parsed
---
This change allows retrieving session keys via API.
---
Documentation already reflects this (currently broken) functionality
---
* [x ] I have explained my PR according to the information in the comments
* [x ] My PR targets the `dev` branch.
=> Add FormParser for session key view

CHANGELOG.md, netbox_secrets/__init__.py, setup.py
=> Handled operational error during collectstatic

netbox_secrets/api/views.py
- The session wasn't working as intended and that's why there was a problem with decryption
=> [Fix]: The session wasn't working for other users

netbox_secrets/migrations/0007_secret__object_repr_secret_comments_and_more.py
- Fix the copy of data in the migration file
=> Fix copy of data in migration

Dockerfile, netbox_secrets/__init__.py, setup.py
- Update NetBox version in Plugin
=> Add support for NetBox v3.6

netbox_secrets/navigation.py
Top Level menu added to Navigation plugin config
=> Top Level menu added to Navigation

docs/rest-api/working-with-secrets.md
=> Add docs howto create session-key

netbox_secrets/api/views.py, netbox_secrets/models/secrets.py, netbox_secrets/tests/test_models.py
=> Code Key Length Fixes

netbox_secrets/filtersets.py, netbox_secrets/forms/filterset.py, netbox_secrets/tests/test_filters.py
=> Update Filtersets and Filterforms with Test Cases

.jscpd.json, .pre-commit-config.yaml, CHANGELOG.md, Dockerfile, README.md, docs/rest-api/working-with-secrets.md, netbox_secrets/__init__.py, netbox_secrets/admin.py, netbox_secrets/api/views.py, netbox_secrets/filtersets.py, netbox_secrets/forms/filterset.py, netbox_secrets/models/secrets.py, netbox_secrets/project-static/package.json, netbox_secrets/project-static/tsconfig.json, netbox_secrets/views.py, setup.py
=> Release v1.10.0

netbox_secrets/views.py
=> Fixes List View action Buttons not Visible

netbox_secrets/api/views.py
=> Fixed failing schema

netbox_secrets/api/views.py, netbox_secrets/graphql/schema.py, netbox_secrets/views.py
- Jira Ticket: [OMS-258](https://onemindservices.atlassian.net/browse/OMS-258)
[OMS-258]: https://onemindservices.atlassian.net/browse/OMS-258?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> OMS-258 Schema Fix

netbox_secrets/api/views.py, netbox_secrets/templates/netbox_secrets/userkey_list.html, netbox_secrets/views.py, setup.py
=> OMS-376 Fix permissions while activating user key

netbox_secrets/__init__.py
- Jira Ticket: [OMS-419](https://onemindservices.atlassian.net/browse/OMS-419)
[OMS-419]: https://onemindservices.atlassian.net/browse/OMS-419?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> OMS-419 fixed runtime warning

CHANGELOG.md, netbox_secrets/__init__.py, netbox_secrets/views.py, setup.py
Thir PR essentially reverts #169 and reintroduces the `Runtime` warning. The generic relation in certain cases do not work.
=> Release v2.1.2

Dockerfile, README.md, netbox_secrets/__init__.py, netbox_secrets/navigation.py, netbox_secrets/template_content.py, netbox_secrets/templates/netbox_secrets/inc/secret_add_button.html, netbox_secrets/urls.py, netbox_secrets/views.py, setup.py
- Jira Ticket: [OMS-453](https://onemindservices.atlassian.net/browse/OMS-453)
[OMS-453]: https://onemindservices.atlassian.net/browse/OMS-453?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> OMS-453 Add support for NetBox v4.2

netbox_secrets/templates/netbox_secrets/inc/secrets_panel.html
- Jira Ticket: [OMS-993](https://onemindservices.atlassian.net/browse/OMS-993)
- **Target Branch:** `dev` 
[OMS-993]: https://onemindservices.atlassian.net/browse/OMS-993?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> OMS-993 Description Field Added to Device Secret View
